config:
  kubernetes:context: deskmini
  home-automation:tailscale-oauth-client-id:
    secure: AAABAD+rc+ryZ3uovz0s/j3z2UnL0laAoK9BVV+2AnFGU1WUgHnV1LzkPOfxWGiIqQ==
  home-automation:tailscale-oauth-client-secret:
    secure: AAABAANm/2PcSr7CuNwZxLUXBAJ39ci58FYQMrIIRTeCBZT+Puu97N25WOdmBZzn/MSr50x7Oi1NlrU0jdkuIr3v4f5eqgfR7uOk2kWWxRbLWPlhaeoCC6Z36nu0MTwn
  home-automation:influxdb-admin-token:
    secure: AAABAJwpPXW77RcoaHzlGYSIfXEhrXkegbFUE2nAoZQKs8H2IY4ZtURkBaHApAIlYpvh/pbgXRFjE/S/fnnbz1X/4dZ54pY8M2ocUyYx4+0JF4FWlK1fd0MWvIqLMbP1x0ecvuVVagrRN4X9WKe7nmReVQpy1jzA
  home-automation:influxdb-admin-password:
    secure: AAABABK584k9ooABvXvSLbmgYPJPiZJzBlxpsU2OardCRJ4QTdALUfiq
  home-automation:home-assistant-token:
    secure: AAABAKBpdSEA83R3T1ayrgdK38OftqNrhDFspKUUtamCb7+0h0T0TqYMAnlP2wgaZqihmKMDbND0UhREPe8C30B5my5RA9c33mX2ZdsGHSX/xVgHsDOscN+l717puWCazXVWgdTXS2INEWMOLzWQGBgG1srKMXgM9wMb6W2wFjr0j0IS471o00xV7Z6JZ61YXr21LJRNy77rifa7h/u78RTBYflncbzPpKEUPw2+n22aESCOJcZ/FI9TOa4qUWuMSLyk28lQ2KLL4VkZV7DUJPHuntKf6uo=
  home-automation:home-assistant-address: 192.168.1.2:8123
