services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - TZ=Europe/Warsaw

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.0.0
    restart: unless-stopped
    depends_on:
      - mosquitto
    network_mode: host
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      # Make sure to verify your USB device path with: ls -l /dev/serial/by-id/
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/Warsaw
    privileged: true

