name: Arduino

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  NODE_IP: 192.168.1.197
  DEVICE_ID: arduino
  PRODUCT_ID: 0x0042
  VENDOR_ID: 0x2341
  FQBN: arduino:avr:mega
  SKETCH: gateway

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install Arduino CLI Boards
        run: |
          arduino-cli core install arduino:avr
      - name: Compile sketch
        run: arduino-cli compile --fqbn ${{ ENV.FQBN }} ${{ ENV.SKETCH }}
        working-directory: arduino/mysensors/gateway
  deployment:
    runs-on: self-hosted
    environment: arduino
    needs: build
    steps:
    - name: List Usb Devices in HA VM
      run: |
        ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "info usbhost"'
    - name: Disconnect Arduino from HA VM
      run: |
        OUTPUT=`ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "device_del arduino"'`
        [ -z "$OUTPUT" ] && echo $OUTPUT || exit 1
    - name: Reconnect Arduino to HA VM
      run: |
        ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "device_add usb-host,vendorid=${{ ENV.VENDOR_ID }},productid=${{ ENV.PRODUCT_ID }},id=${{ ENV.DEVICE_ID }}"'
    - name: List Usb Devices in HA VM (again)
      run: |
        ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "info usbhost"'
