name: Arduino

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: List Usb Devices
      run: pvesh create /nodes/pve/qemu/102/monitor --command "info usbhost"
