name: Arduino

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  NODE_IP: 192.168.1.197
  DEVICE_ID: arduino
  PRODUCT_ID: 0x0042
  VENDOR_ID: 0x2341

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: List Usb Devices
      run: ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "info usbhost"'
