name: Arduino

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  NODE_IP: 192.168.1.197
  DEVICE_ID: arduino
  PRODUCT_ID: 0x0042
  VENDOR_ID: 0x2341
  FQBN: arduino:avr:mega
  SKETCH: gateway
  PORT: 01

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Add Arduino Libs
        run: |
          arduino-cli core install arduino:avr@1.8.2         
          arduino-cli lib install ArduinoSTL
          arduino-cli lib install MySensors@2.3.2
          arduino-cli lib install OneButton@1.4.0
      - name: Compile sketch
        run: arduino-cli compile --fqbn ${{ ENV.FQBN }} ${{ ENV.SKETCH }} --build-path release/
        working-directory: arduino/mysensors/gateway
      - uses: actions/upload-artifact@v3
        with:
          name: gateway_release_${{ github.run_id }}
          path: arduino/mysensors/gateway/
  deployment:
    runs-on: self-hosted
    environment: arduino
    concurrency: arduino
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: gateway_release_${{ github.run_id }}
    - name: ls -la
      run: ls -la
    - name: List Usb Devices in HA VM
      run: |
        ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "info usbhost"'
    - name: Disconnect Arduino from HA VM
      run: |
        ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "device_del arduino"'
    - name: Upload Sketch to pve node
      run: |
        scp -r ./ root@${{ ENV.NODE_IP }}:/release
        ssh root@${{ ENV.NODE_IP }} cd /release && arduino-cli upload . --input-dir release/ --fqbn ${{ ENV.FQBN }} --port ${{ ENV.PORT }} --verify
        working-directory: arduino/mysensors/gateway
    - name: Reconnect Arduino to HA VM
      run: |
        ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "device_add usb-host,vendorid=${{ ENV.VENDOR_ID }},productid=${{ ENV.PRODUCT_ID }},id=${{ ENV.DEVICE_ID }}"'
    - name: List Usb Devices in HA VM (again)
      run: |
        ssh root@${{ ENV.NODE_IP }} 'pvesh create /nodes/pve/qemu/102/monitor --command "info usbhost"'
